### PR TITLE
demo tests on archer2 with XIOS3

### PR DESCRIPTION
**Pull request by mo-marqh**
demonstration code running on Archer2 with environment switches to enable different XIOS versions

### CODE REVIEW

**Comment by jeff-cole** [comment]
I independently ran this on archer2 and got the expected result
```
----------------------------------------------------------------------
Ran 8 tests in 21.098s

OK (skipped=6)
```
Also ran with a XIOS2 trunk_r2252 installation under my account and set MVER to a null value and this also worked as expected
```
----------------------------------------------------------------------
Ran 8 tests in 25.565s

OK (expected failures=3)-
```

**Comment by jeff-cole** [comment]
I'm a bit confused between usage of NETCDF_LIB_DIR/NETCDF_INC_DIR and NETCDF_LIBDIR/NETCDF_INCDIR. The Makefile says it expects NETCDF_LIB_DIR/NETCDF_INC_DIR but uses NETCDF_LIBDIR/NETCDF_INCDIR and desktopEnv defines NETCDF_LIB_DIR/NETCDF_INC_DIR but archerEnv defines NETCDF_LIBDIR/NETCDF_INCDIR

**Comment by mo-marqh** [comment]
> I'm a bit confused between usage of NETCDF_LIB_DIR/NETCDF_INC_DIR and NETCDF_LIBDIR/NETCDF_INCDIR. The Makefile says it expects NETCDF_LIB_DIR/NETCDF_INC_DIR but uses NETCDF_LIBDIR/NETCDF_INCDIR and desktopEnv defines NETCDF_LIB_DIR/NETCDF_INC_DIR but archerEnv defines NETCDF_LIBDIR/NETCDF_INCDIR

thanks for raising this @jeff-cole 

There is some confusion in the code and documentation, with the Makefile doc string being wrong compared to the implementation, as you identified.
I've tried to address this with the latest commit.

The issue being addressed is that some platforms separate the NetCDF install areas, such that multiple netcdf locations are required for compilation, whilst other platforms collect all this in one location.
To maintain multi-platform compatibility, there's a bit of (clumsy ?) scripting for the github action runner and desktop to take a list of netCDF locations and process them into Makefile compatible entities.

I've renamed `NETCDF_LIB_DIR` to `NETCDF_LIB_DIRS` to try and make this multiplicity clear, and updated to Makefile comment to be consistent.

Does this seem more clear now?
Are there different ways to solve this issue that you might prefer

**Review by jeff-cole — APPROVED** [review]
Archer2 additions work as expected + useful clarifications for netCDF environment variables and elimination of repeated Makefile files

**Pull request merged**
